# Generated by Django 3.1.7 on 2021-06-24 06:56

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('short_description', models.TextField(max_length=250)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='basic',
            name='copyright_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic',
            name='footer_background',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='site_pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic',
            name='footer_contact_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basic',
            name='footer_description',
            field=models.TextField(),
        ),
    ]