# Generated by Django 3.1.7 on 2021-06-24 08:38

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0002_auto_20210624_1256'),
    ]

    operations = [
    
      ]
