# Generated by Django 3.1.7 on 2021-06-24 08:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(null=True, upload_to='p_images')),
                ('gallery_images', models.ImageField(null=True, upload_to='p_images')),
                ('title', models.CharField(max_length=250)),
                ('price_us', models.CharField(max_length=250, null=True)),
                ('listing_type', models.CharField(max_length=250, null=True)),
                ('perperty_type', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('lot_Size_m2', models.CharField(max_length=30, null=True)),
                ('lot_Size_ft2', models.CharField(max_length=30, null=True)),
                ('floor_size_m2', models.CharField(max_length=30, null=True)),
                ('floor_size_ft2', models.CharField(max_length=30, null=True)),
                ('floors', models.CharField(max_length=30, null=True)),
                ('beds', models.CharField(max_length=6, null=True)),
                ('baths', models.CharField(max_length=6, null=True)),
                ('property_id', models.CharField(max_length=30, null=True)),
                ('short_description', models.CharField(max_length=150, null=True)),
                ('details', tinymce.models.HTMLField(null=True)),
                ('category', models.ManyToManyField(related_name='Category', to='properties.Property_categories')),
            ],
        ),
    ]
