# Generated by Django 3.1.7 on 2021-06-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210624_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='perperty_type',
        ),
        migrations.RemoveField(
            model_name='property_features',
            name='property_category',
        ),
    ]
