# Generated by Django 3.1.7 on 2021-06-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210624_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='perperty_type',
            new_name='property_type',
        ),
    ]
