# Generated by Django 3.1.7 on 2021-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210624_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.AlterField(
            model_name='property_categories',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
