# Generated by Django 3.1.7 on 2021-06-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20210624_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property_categories',
            new_name='Property_category',
        ),
    ]
