# Generated by Django 3.1.7 on 2021-06-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20210624_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_category',
        ),
        migrations.DeleteModel(
            name='Property_features',
        ),
    ]
