# Generated by Django 3.1.7 on 2021-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_category_property_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property_category',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(to='properties.Category'),
        ),
    ]
