# Generated by Django 3.1.7 on 2021-06-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20210624_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='feature',
            field=models.ManyToManyField(related_name='Features', to='properties.Property_features'),
        ),
    ]
