# Generated by Django 3.1.7 on 2021-06-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20210625_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_us',
        ),
    ]
