# Generated by Django 3.1.7 on 2021-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_remove_property_price_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_us',
            field=models.IntegerField(null=True),
        ),
    ]
