# Generated by Django 3.1.7 on 2021-06-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_price_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='property',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_size_ft2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_size_m2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lot_Size_ft2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lot_Size_m2',
        ),
    ]
