# Generated by Django 3.1.7 on 2021-06-26 02:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20210625_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='property',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AlterField(
            model_name='property',
            name='details',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='p_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size_ft2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size_m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery_images',
            field=models.ImageField(blank=True, null=True, upload_to='p_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_Size_ft2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_Size_m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property_features',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
