# Generated by Django 3.1.7 on 2021-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_auto_20210626_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.ManyToManyField(to='properties.Baths'),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.ManyToManyField(to='properties.Beds'),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.ManyToManyField(to='properties.Floors'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ManyToManyField(to='properties.Location'),
        ),
    ]
