# Generated by Django 3.1.7 on 2021-06-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20210626_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='baths',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.ManyToManyField(blank=True, null=True, to='properties.Baths'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.ManyToManyField(blank=True, null=True, to='properties.Beds'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.ManyToManyField(blank=True, to='properties.Floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='properties.Location'),
        ),
        migrations.AlterField(
            model_name='property_features',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.cars'),
        ),
    ]
