# Generated by Django 3.1.7 on 2021-06-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20210628_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='test',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
