# Generated by Django 3.1.7 on 2021-06-28 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_auto_20210628_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='gallery_images',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='property_images')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
