# Generated by Django 3.1.7 on 2021-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_remove_property_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.ManyToManyField(blank=True, default=None, to='properties.Baths'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.ManyToManyField(blank=True, default=None, to='properties.Beds'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, to='properties.Location'),
        ),
    ]
