# Generated by Django 3.1.7 on 2021-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_property_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=None),
        ),
    ]
