# Generated by Django 3.1.7 on 2021-07-01 09:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_auto_20210701_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(default=None, to='properties.Category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='details',
            field=tinymce.models.HTMLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='feature',
            field=models.ManyToManyField(default=None, related_name='Features', to='properties.Property_features'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, default=None, upload_to='p_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size_ft2',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size_m2',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.ManyToManyField(blank=True, default=None, to='properties.Floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_Size_ft2',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_Size_m2',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_us',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
