# Generated by Django 3.1.7 on 2021-07-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_lovedproperties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lovedproperties',
            old_name='property',
            new_name='title',
        ),
    ]
