# Generated by Django 3.1.7 on 2021-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_lovedproperties_lovedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.TextField(default=None, help_text='For under title description and SEO', max_length=500),
        ),
    ]
