# Generated by Django 3.1.7 on 2021-07-18 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_auto_20210718_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='last_modified',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.TextField(default=None, help_text='For under title description and SEO', max_length=1500),
        ),
    ]
