# Generated by Django 3.1.7 on 2021-07-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_property_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
