# Generated by Django 3.1.7 on 2021-07-28 13:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_remove_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
