# Generated by Django 3.1.7 on 2021-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, default=models.CharField(max_length=250), max_length=50, null=True),
        ),
    ]
