# Generated by Django 3.1.7 on 2021-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_property_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seo_description',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, default=models.CharField(max_length=250), max_length=60, null=True),
        ),
    ]
