# Generated by Django 3.1.7 on 2021-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_remove_property_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
