# Generated by Django 3.1.7 on 2021-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_property_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='seo_description',
            field=models.TextField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
