# Generated by Django 3.1.7 on 2021-07-28 16:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_auto_20210728_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='properties.Baths'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='properties.Beds'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(default=None, null=True, to='properties.Category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='details',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size_ft2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size_m2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='properties.Floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_modified',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='properties.Location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_Size_ft2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_Size_m2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_us',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
