# Generated by Django 3.1.7 on 2021-06-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bannerHomeMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=20)),
                ('button_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='property_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('featured_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('background', models.ImageField(upload_to='site_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=50)),
                ('client_title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='others')),
            ],
        ),
    ]
