# Generated by Django 3.1.7 on 2021-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
       
    ]
